# Generated by Django 5.2.1 on 2025-05-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone (ex: bi-wrench)', max_length=50)),
                ('categoria', models.CharField(choices=[('restauro', 'Restauro e Mecânica'), ('estetica', 'Estética e Conservação'), ('documentacao', 'Documentação'), ('pecas', 'Peças e Customização'), ('complementar', 'Serviços Complementares'), ('consultoria', 'Consultoria e Comunidade')], max_length=50)),
                ('destaque', models.BooleanField(default=False)),
            ],
        ),
    ]
